<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="MAIN" Id="{252640da-6020-4c12-a241-c1e4382f809e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	basgMotion : Servo;
	i: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[basgMotion(HMI_MODE:=TRUE);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>